captureDirectory: ./captures
completeDirectory: ./complete
modelScanInterval: 30
createModelDirectory: true
dateFormat: YYYYMMDD-HHmmss
minFileSizeMb: 10
port: 9081
debug: true
models: []
queue: []
rtmpDebug: false
