captureDirectory: ./captures
completeDirectory: ./complete
modelScanInterval: 30
createModelDirectory: true
dateFormat: YYYYMMDD-HHmmss
minFileSizeMb: 10
port: 9080
debug: true
models: []
queue: []
rtmp: false
proxyServer: '54.206.109.161:9090'
